### ISSUE TITLE
DuckDuckGo Privacy Browser not supported

### ISSUE THREAD

**Issue by brindy** [peter-iakovlev/TelegramUI#3]
Please add support for opening links in DuckDuckGo Privacy Browser.

I created a PR for this on the old code base so all the information required should be there:
https://github.com/peter-iakovlev/Telegram/pull/278/files

Thanks in advance!

**Comment by laktyushin** [comment]
DuckDuckGo Privacy Browser added in v5.6.

**Comment by brindy** [comment]
Thank you!
